name: dexmate
base: core22
version: git
summary: Intuitive Dexcom CGM monitoring app
description: |
  DexMate provides real-time glucose monitoring with trends, 
  notifications, and data visualization for Dexcom CGM users.
  Note: This is not a medical device.
grade: stable
confinement: strict

apps:
  dexmate:
    command: bin/dexmate-wrapper
    desktop: usr/share/applications/dexmate.desktop
    plugs:
      - desktop
      - home
      - network
      - network-bind
      - opengl
      - pulseaudio
      - x11
      - wayland
      - gsettings

parts:
  app:
    plugin: python
    source: src
    build-packages:
      - git
      - gfortran
      - libblas-dev
      - liblapack-dev
      - pkg-config
      - python3-dev
      - build-essential
    python-packages:
      - pydexcom
      - notify_py
      - scikit-learn
      - scipy==1.13.0  # Pinned version
      - cryptography
      - requests
      - pillow
      - packaging
      - pyinstaller  # Add pyinstaller to build executable
    stage-packages:
      - libglib2.0-0
      - libgtk-3-0
      - libgdk-pixbuf-2.0-0
      - libx11-6
      - libxcb1
      - libxau6
      - libnotify4
    # Add build step to create the executable
    override-build: |
      # First run default python build
      snapcraftctl build
      
      # Then build executable with PyInstaller
      pyinstaller --onefile Dex_new.py --name DexMate
      
      # Install the binary to bin/ directory
      mkdir -p $SNAPCRAFT_PART_INSTALL/bin
      cp dist/DexMate $SNAPCRAFT_PART_INSTALL/bin/

  wrapper:
    plugin: dump
    source: assets/wrapper
    override-build: |
      chmod 755 $SNAPCRAFT_PART_SRC/dexmate-wrapper
      snapcraftctl build
    organize:
      dexmate-wrapper: bin/dexmate-wrapper

  desktop:
    plugin: dump
    source: assets/gui
    organize:
      dexmate.desktop: usr/share/applications/dexmate.desktop
      logo.png: meta/gui/logo.png