name: dexmate
base: core22
version: '2.0.0'
summary: Intuitive app for reviewing and monitoring Dexcom CGM data
description: |
  DexMate is an open-source tool for displaying real-time glucose levels from Dexcom CGM, 
  including trends, delta values, and notifications — *not a substitute for medical care*.
grade: stable
confinement: strict

apps:
  dexmate:
    command: bin/dexmate-wrapper
    desktop: usr/share/applications/dexmate.desktop
    plugs:
      - desktop
      - home
      - network
      - network-bind
      - opengl
      - pulseaudio
      - x11
      - wayland
      - gsettings

parts:
  app:
    plugin: python
    source: src
    python-packages:
      - pydexcom
      - notify-py
      - scikit-learn
      - cryptography
      - requests
      - pillow
    stage-packages:
      - libglib2.0-0
      - libgtk-3-0
      - libx11-6
      - libgdk-pixbuf-2.0-0
      - libnotify4
      - libnss3

  wrapper:
    plugin: dump
    source: snap/wrapper
    organize:
      dexmate-wrapper: bin/dexmate-wrapper

  desktop:
    plugin: dump
    source: snap/gui
    organize:
      dexmate.desktop: usr/share/applications/dexmate.desktop
      logo.png: meta/gui/logo.png
