name: dexmate
base: core22
version: git
summary: Intuitive Dexcom CGM monitoring app
description: |
  DexMate provides real-time glucose monitoring with trends, 
  notifications, and data visualization for Dexcom CGM users.
  Note: This is not a medical device.
grade: stable
confinement: strict

apps:
  dexmate:
    command: bin/dexmate-wrapper
    desktop: usr/share/applications/dexmate.desktop
    plugs:
      - desktop
      - home
      - network
      - network-bind
      - opengl
      - pulseaudio
      - x11
      - wayland
      - gsettings
    environment:
      PATH: $SNAP/usr/sbin:$SNAP/usr/bin:$SNAP/sbin:$SNAP/bin:$PATH

parts:
  app:
    plugin: python
    source: src
    build-packages:
      - git
      - gfortran
      - libblas-dev
      - liblapack-dev
      - pkg-config
      - python3-dev
      - build-essential
      - liblzma-dev
      - libbz2-dev
    python-packages:
      - pyinstaller
      - pydexcom
      - notify_py
      - scikit-learn
      - scipy==1.13.0
      - cryptography
      - requests
      - pillow
      - packaging
    stage-packages:
      - libglib2.0-0
      - libgtk-3-0
      - libgdk-pixbuf-2.0-0
      - libx11-6
      - libxcb1
      - libxau6
      - libnotify4
    override-build: |
      # Build the executable with PyInstaller
      pyinstaller --onefile Dex_new.py --name DexMate --add-data "logo_png.png:." 
      
      # Install the binary to bin/
      mkdir -p $SNAPCRAFT_PART_INSTALL/bin
      cp dist/DexMate $SNAPCRAFT_PART_INSTALL/bin/dexmate
      
      # Install the logo to share/
      mkdir -p $SNAPCRAFT_PART_INSTALL/share
      cp logo_png.png $SNAPCRAFT_PART_INSTALL/share/logo.png

  wrapper:
    plugin: dump
    source: assets/wrapper
    override-build: |
      chmod 755 $SNAPCRAFT_PART_SRC/dexmate-wrapper
      snapcraftctl build
    organize:
      dexmate-wrapper: bin/dexmate-wrapper

  desktop:
    plugin: dump
    source: assets/gui
    organize:
      dexmate.desktop: usr/share/applications/dexmate.desktop