name: dexmate
base: core22
version: git
summary: Intuitive Dexcom CGM monitoring app
description: Real-time glucose levels with trends and notifications
grade: stable
confinement: strict

apps:
  dexmate:
    command: bin/dexmate-wrapper
    desktop: usr/share/applications/dexmate.desktop
    plugs:
      - desktop
      - network
      - home
      - opengl
      - pulseaudio
      - gsettings

parts:
  app:
    plugin: python
    source: src
    python-packages:
      - pydexcom
      - notify-py
      - scikit-learn
      - cryptography
      - requests
      - pillow
    stage-packages:
      - libglib2.0-0
      - libgtk-3-0
      - libgdk-pixbuf-2.0-0

  wrapper:
    plugin: dump
    source: snap_assets/wrapper
    organize:
      dexmate-wrapper: bin/dexmate-wrapper

  desktop:
    plugin: dump
    source: snap_assets/gui
    organize:
      dexmate.desktop: usr/share/applications/dexmate.desktop
      logo.png: meta/gui/logo.png