name: dexmate
base: core22
version: git
summary: Intuitive Dexcom CGM monitoring app
description: |
  DexMate provides real-time glucose monitoring with trends, 
  notifications, and data visualization for Dexcom CGM users.
  Note: This is not a medical device.
grade: stable
confinement: strict

apps:
  dexmate:
    command: bin/dexmate-wrapper
    desktop: usr/share/applications/dexmate.desktop
    plugs:
      - desktop
      - home
      - network
      - network-bind
      - opengl
      - pulseaudio
      - x11
      - wayland
      - gsettings
    environment:
      # Ensure Python finds Tkinter libraries
      LD_LIBRARY_PATH: $SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/tk8.6:$SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/tcl8.6:$LD_LIBRARY_PATH

parts:
  app:
    plugin: python
    source: src
    build-packages:
      - git
      - gfortran
      - libblas-dev
      - liblapack-dev
      - pkg-config
      - python3-dev
      - build-essential
      - python3-tk  # Required for tkinter
      - tcl-dev
      - tk-dev
    python-packages:
      - pyinstaller
      - pydexcom
      - notify_py
      - scikit-learn
      - scipy==1.13.0
      - cryptography
      - requests
      - pillow
      - packaging
    stage-packages:
      - libglib2.0-0
      - libgtk-3-0
      - libgdk-pixbuf-2.0-0
      - libx11-6
      - libxcb1
      - libxau6
      - libnotify4
      - python3-tk  # Required at runtime
      - tcl8.6
      - tk8.6
    override-build: |
      # First run default python build
      snapcraftctl build
      
      # Then build executable with PyInstaller
      # Explicitly include Tcl/Tk directories
      pyinstaller --onefile Dex_new.py --name dexmate \
        --paths $SNAPCRAFT_PART_INSTALL/usr/lib/python3.*/site-packages \
        --add-data "$SNAPCRAFT_PART_INSTALL/usr/lib/python3.*/tkinter:tkinter"
      
      # Install the binary to bin/ directory
      mkdir -p $SNAPCRAFT_PART_INSTALL/bin
      cp dist/dexmate $SNAPCRAFT_PART_INSTALL/bin/

  wrapper:
    plugin: dump
    source: assets/wrapper
    override-build: |
      chmod 755 $SNAPCRAFT_PART_SRC/dexmate-wrapper
      snapcraftctl build
    organize:
      dexmate-wrapper: bin/dexmate-wrapper

  desktop:
    plugin: dump
    source: assets/gui
    organize:
      dexmate.desktop: usr/share/applications/dexmate.desktop
      logo.png: meta/gui/logo.png