name: dexmate
base: core22
version: git
summary: Intuitive Dexcom CGM monitoring app
description: |
  DexMate provides real-time glucose monitoring with trends, 
  notifications, and data visualization for Dexcom CGM users.
  Note: This is not a medical device.
grade: stable
confinement: strict

apps:
  dexmate:
    command: bin/dexmate-wrapper
    desktop: usr/share/applications/dexmate.desktop
    plugs:
      - desktop
      - home
      - network
      - network-bind
      - opengl
      - pulseaudio
      - x11
      - wayland
      - gsettings
    environment:
      # Required for Tkinter (GUI) to find its libraries
      LD_LIBRARY_PATH: $SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/tk8.6:$SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/tcl8.6:$LD_LIBRARY_PATH

parts:
  dexmate:
    plugin: nil
    source: src
    build-packages:
      - git
      - python3-dev
      - python3-tk
      - build-essential
      - libblas-dev
      - liblapack-dev
      - pkg-config
      - gfortran
      - python3-pip
      - pyinstaller
      - tcl-dev
      - tk-dev
    stage-packages:
      - libglib2.0-0
      - libgtk-3-0
      - libgdk-pixbuf-2.0-0
      - libx11-6
      - libxcb1
      - libxau6
      - libnotify4
      - python3-tk
      - tcl8.6
      - tk8.6
    override-build: |
      snapcraftctl build
    
      # Install Python dependencies to a local directory
      pip3 install --target=lib \
        pydexcom notify-py scikit-learn scipy==1.13.0 \
        cryptography requests pillow packaging
    
      # Install PyInstaller globally for the build process
      pip3 install pyinstaller
    
      # Build the standalone binary
      pyinstaller Dex_new.py \
        --name dexmate \
        --onefile \
        --add-data "logo_png.png:." \
        --paths=lib
    
      mkdir -p $SNAPCRAFT_PART_INSTALL/bin
      cp dist/dexmate $SNAPCRAFT_PART_INSTALL/bin/


  wrapper:
    plugin: dump
    source: assets/wrapper
    override-build: |
      chmod +x $SNAPCRAFT_PART_SRC/dexmate-wrapper
      snapcraftctl build
    organize:
      dexmate-wrapper: bin/dexmate-wrapper

  desktop:
    plugin: dump
    source: assets/gui
    organize:
      dexmate.desktop: usr/share/applications/dexmate.desktop
      logo_png.png: meta/gui/logo_png.png
