name: Build Snap Package

on:
  push:
    branches: [main]
  release:
    types: [created]

permissions:
  contents: write

jobs:
  build-snap:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install Snapcraft
      run: |
        sudo snap install snapcraft --classic
        sudo snap install lxd
        sudo lxd init --auto
        sudo usermod -a -G lxd $USER
        newgrp lxd

    - name: Build Snap locally
      run: |
        snapcraft --use-lxd
        mv *.snap dexmate.snap

    - name: Upload Snap artifact
      uses: actions/upload-artifact@v4
      with:
        name: dexmate-snap
        path: dexmate.snap
        retention-days: 5

    - name: Upload to Snap Store (on release)
      if: github.event_name == 'release'
      run: |
        snapcraft upload --release=stable dexmate.snap
      env:
        SNAPCRAFT_STORE_CREDENTIALS: ${{ secrets.SNAPCRAFT_STORE_CREDENTIALS }}