name: Build Snap Package

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

jobs:
  build-snap:
    runs-on: ubuntu-24.04
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y snapd squashfuse fuse
        sudo systemctl start snapd

    - name: Install Snapcraft and LXD
      run: |
        sudo snap install core
        sudo snap install snapcraft --classic
        sudo snap install lxd
        sudo lxd init --auto
        sudo usermod -a -G lxd $USER
        sudo chmod a+rwx /var/snap/lxd/common/lxd/

    - name: Build Snap
      run: |
        # Use a workaround for group permissions
        sudo chmod 0660 /var/snap/lxd/common/lxd/unix.socket
        sudo chown root:lxd /var/snap/lxd/common/lxd/unix.socket
        snapcraft --use-lxd
        mv *.snap dexmate.snap

    - name: Upload Snap artifact
      uses: actions/upload-artifact@v4
      with:
        name: dexmate-snap
        path: dexmate.snap
        retention-days: 7