name: Build Snap Package

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

jobs:
  build-snap:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Snapcraft
      uses: snapcore/actions/setup-snapcraft@v1
      with:
        snapcraft-channel: latest/stable

    - name: Install LXD
      run: |
        sudo snap install lxd
        sudo lxd init --auto
        sudo usermod -aG lxd $USER
        sudo chmod a+rw /var/snap/lxd/common/lxd/unix.socket

    - name: Build Snap
      run: |
        snapcraft --use-lxd
        mv *.snap dexmate.snap

    - name: Upload Snap artifact
      uses: actions/upload-artifact@v4
      with:
        name: dexmate-snap
        path: dexmate.snap
        retention-days: 7